import type { ConceptGraph, ConceptNode } from "./types";

const CONCEPTS: ConceptNode[] = [
  {
    conceptKey: "tactical_awareness",
    conceptName: "Tactical Awareness",
    conceptCategory: "tactical",
    parentConcepts: [],
    childConcepts: ["fork", "pin", "skewer", "discovered_attack", "overload", "deflection", "back_rank", "hanging_piece", "king_attack"],
    relatedConcepts: ["initiative", "piece_activity"],
    prerequisiteConcepts: [],
    difficultyBand: "foundation",
    trainingTags: ["tactics", "calculation"],
    lessonCategories: ["tactical_miss", "calculation_error", "critical_defense", "material_loss"],
    reasonCodes: ["high_eval_swing", "critical_position", "blunder", "long_calculation"],
  },
  {
    conceptKey: "hanging_piece",
    conceptName: "Hanging Piece",
    conceptCategory: "tactical",
    parentConcepts: ["tactical_awareness"],
    childConcepts: [],
    relatedConcepts: ["fork", "deflection"],
    prerequisiteConcepts: ["tactical_awareness"],
    difficultyBand: "foundation",
    trainingTags: ["material", "loose-pieces"],
    lessonCategories: ["material_loss"],
    reasonCodes: ["blunder", "high_eval_swing"],
  },
  {
    conceptKey: "fork",
    conceptName: "Fork",
    conceptCategory: "tactical",
    parentConcepts: ["tactical_awareness"],
    childConcepts: [],
    relatedConcepts: ["skewer", "discovered_attack"],
    prerequisiteConcepts: ["tactical_awareness"],
    difficultyBand: "foundation",
    trainingTags: ["double-attack"],
    lessonCategories: ["tactical_miss", "calculation_error"],
    reasonCodes: ["high_eval_swing", "long_calculation"],
  },
  {
    conceptKey: "pin",
    conceptName: "Pin",
    conceptCategory: "tactical",
    parentConcepts: ["tactical_awareness"],
    childConcepts: [],
    relatedConcepts: ["skewer", "back_rank"],
    prerequisiteConcepts: ["tactical_awareness"],
    difficultyBand: "foundation",
    trainingTags: ["constraint", "piece-pressure"],
    lessonCategories: ["tactical_miss", "critical_defense"],
    reasonCodes: ["critical_position", "long_calculation"],
  },
  {
    conceptKey: "skewer",
    conceptName: "Skewer",
    conceptCategory: "tactical",
    parentConcepts: ["tactical_awareness"],
    childConcepts: [],
    relatedConcepts: ["pin", "fork"],
    prerequisiteConcepts: ["tactical_awareness"],
    difficultyBand: "core",
    trainingTags: ["line-tactics"],
    lessonCategories: ["tactical_miss", "calculation_error"],
    reasonCodes: ["high_eval_swing", "long_calculation"],
  },
  {
    conceptKey: "discovered_attack",
    conceptName: "Discovered Attack",
    conceptCategory: "tactical",
    parentConcepts: ["tactical_awareness"],
    childConcepts: [],
    relatedConcepts: ["initiative", "deflection"],
    prerequisiteConcepts: ["tactical_awareness"],
    difficultyBand: "core",
    trainingTags: ["line-opening", "tempo"],
    lessonCategories: ["calculation_error", "tactical_miss"],
    reasonCodes: ["long_calculation", "high_eval_swing"],
  },
  {
    conceptKey: "overload",
    conceptName: "Overload",
    conceptCategory: "tactical",
    parentConcepts: ["tactical_awareness"],
    childConcepts: [],
    relatedConcepts: ["deflection", "back_rank"],
    prerequisiteConcepts: ["tactical_awareness"],
    difficultyBand: "advanced",
    trainingTags: ["defensive-collapse"],
    lessonCategories: ["calculation_error", "critical_defense"],
    reasonCodes: ["critical_position", "long_calculation"],
  },
  {
    conceptKey: "deflection",
    conceptName: "Deflection",
    conceptCategory: "tactical",
    parentConcepts: ["tactical_awareness"],
    childConcepts: [],
    relatedConcepts: ["overload", "king_attack"],
    prerequisiteConcepts: ["tactical_awareness"],
    difficultyBand: "core",
    trainingTags: ["remove-defender"],
    lessonCategories: ["tactical_miss", "critical_defense"],
    reasonCodes: ["critical_position", "high_eval_swing"],
  },
  {
    conceptKey: "back_rank",
    conceptName: "Back Rank",
    conceptCategory: "tactical",
    parentConcepts: ["tactical_awareness"],
    childConcepts: [],
    relatedConcepts: ["pin", "king_attack"],
    prerequisiteConcepts: ["tactical_awareness"],
    difficultyBand: "foundation",
    trainingTags: ["mating-net", "king-safety"],
    lessonCategories: ["tactical_miss", "critical_defense"],
    reasonCodes: ["critical_position", "high_eval_swing"],
  },
  {
    conceptKey: "king_attack",
    conceptName: "King Attack",
    conceptCategory: "tactical",
    parentConcepts: ["tactical_awareness"],
    childConcepts: [],
    relatedConcepts: ["initiative", "piece_activity", "back_rank"],
    prerequisiteConcepts: ["tactical_awareness", "initiative"],
    difficultyBand: "advanced",
    trainingTags: ["attack", "coordination"],
    lessonCategories: ["tactical_miss", "critical_defense", "opening_inaccuracy"],
    reasonCodes: ["critical_position", "high_eval_swing"],
  },
  {
    conceptKey: "endgame_conversion",
    conceptName: "Endgame Conversion",
    conceptCategory: "endgame",
    parentConcepts: [],
    childConcepts: [],
    relatedConcepts: ["initiative", "pawn_structure", "piece_activity"],
    prerequisiteConcepts: ["piece_activity"],
    difficultyBand: "core",
    trainingTags: ["endgame", "technique"],
    lessonCategories: ["endgame_technique"],
    reasonCodes: ["endgame_mistake", "late_blunder"],
  },
  {
    conceptKey: "opening_development",
    conceptName: "Opening Development",
    conceptCategory: "opening",
    parentConcepts: [],
    childConcepts: [],
    relatedConcepts: ["king_safety", "center_control", "piece_activity"],
    prerequisiteConcepts: [],
    difficultyBand: "foundation",
    trainingTags: ["opening", "development"],
    lessonCategories: ["opening_inaccuracy"],
    reasonCodes: ["opening_error"],
    openingFamilies: ["italian_game", "ruy_lopez", "queens_gambit", "sicilian_defense", "french_defense", "caro_kann", "kings_indian", "english_opening"],
  },
  {
    conceptKey: "center_control",
    conceptName: "Center Control",
    conceptCategory: "opening",
    parentConcepts: [],
    childConcepts: [],
    relatedConcepts: ["opening_development", "initiative", "pawn_structure"],
    prerequisiteConcepts: [],
    difficultyBand: "foundation",
    trainingTags: ["opening", "center"],
    lessonCategories: ["opening_inaccuracy", "positional_error"],
    reasonCodes: ["opening_error"],
    openingFamilies: ["sicilian_defense", "french_defense", "caro_kann", "queens_gambit"],
  },
  {
    conceptKey: "king_safety",
    conceptName: "King Safety",
    conceptCategory: "opening",
    parentConcepts: [],
    childConcepts: [],
    relatedConcepts: ["opening_development", "back_rank", "king_attack"],
    prerequisiteConcepts: ["opening_development"],
    difficultyBand: "foundation",
    trainingTags: ["castling", "safety"],
    lessonCategories: ["opening_inaccuracy", "critical_defense"],
    reasonCodes: ["opening_error", "critical_position"],
    openingFamilies: ["italian_game", "ruy_lopez", "sicilian_defense", "kings_indian"],
  },
  {
    conceptKey: "pawn_structure",
    conceptName: "Pawn Structure",
    conceptCategory: "positional",
    parentConcepts: [],
    childConcepts: [],
    relatedConcepts: ["piece_activity", "center_control", "endgame_conversion"],
    prerequisiteConcepts: [],
    difficultyBand: "core",
    trainingTags: ["structure", "planning"],
    lessonCategories: ["positional_error", "opening_inaccuracy", "endgame_technique"],
    reasonCodes: ["opening_error", "endgame_mistake"],
  },
  {
    conceptKey: "initiative",
    conceptName: "Initiative",
    conceptCategory: "positional",
    parentConcepts: [],
    childConcepts: [],
    relatedConcepts: ["piece_activity", "king_attack", "discovered_attack"],
    prerequisiteConcepts: ["opening_development"],
    difficultyBand: "core",
    trainingTags: ["tempo", "pressure"],
    lessonCategories: ["positional_error", "calculation_error", "tactical_miss"],
    reasonCodes: ["long_calculation", "near_equality"],
  },
  {
    conceptKey: "piece_activity",
    conceptName: "Piece Activity",
    conceptCategory: "positional",
    parentConcepts: [],
    childConcepts: [],
    relatedConcepts: ["initiative", "opening_development", "endgame_conversion"],
    prerequisiteConcepts: [],
    difficultyBand: "foundation",
    trainingTags: ["coordination", "improvement"],
    lessonCategories: ["positional_error", "opening_inaccuracy", "endgame_technique"],
    reasonCodes: ["opening_error", "near_equality", "endgame_mistake"],
  },
];

export function buildConceptGraph(generatedAt: string = new Date().toISOString()): ConceptGraph {
  const concepts = CONCEPTS.map((concept) => ({
    ...concept,
    parentConcepts: [...concept.parentConcepts],
    childConcepts: [...concept.childConcepts],
    relatedConcepts: [...concept.relatedConcepts],
    prerequisiteConcepts: [...concept.prerequisiteConcepts],
    trainingTags: [...concept.trainingTags],
    lessonCategories: [...concept.lessonCategories],
    reasonCodes: [...concept.reasonCodes],
    openingFamilies: concept.openingFamilies ? [...concept.openingFamilies] : undefined,
  }));

  const conceptIndex = Object.fromEntries(concepts.map((concept) => [concept.conceptKey, concept]));
  const categories = ["tactical", "positional", "endgame", "opening", "meta"] as const;
  const categorySummaries = categories
    .map((category) => {
      const nodes = concepts.filter((concept) => concept.conceptCategory === category);
      return {
        category,
        conceptCount: nodes.length,
        concepts: nodes.map((node) => node.conceptKey),
      };
    })
    .filter((entry) => entry.conceptCount > 0);

  return {
    generatedAt,
    concepts,
    conceptIndex,
    categorySummaries,
  };
}
